config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
    resources :comments
  end
  devise_for :users
  get 'open-issues', to: "tickets#open_issues"
  root to: 'homes#index'
  resources :users, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ticket
  belongs_to :user

  validates :reply, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :title, presence: true
  validates :message, presence: true
  validates :category, presence: true
  validates :priority, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :tickets, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :full_name, presence: true
  validates :username, presence: true
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :username, :email, :password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:edit, :update, :show, :destroy]
  before_action :set_ticket

  def new
    @comment = Comment.new
  end

  def create
    @comment = @ticket.comments.create(params[:comment].permit(:reply, :meeting_id))
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to ticket_path(@ticket) }
        format.js
      else
        format.html { redirect_to ticket_path(@ticket), notice: "Your ticket did not save. Please try again" }
        format.js
      end
    end
  end

  def destroy
    @comment = @ticket.comments.find(params[:id])
    @comment.destroy
    redirect_to ticket_path(@ticket)
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:reply)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :must_be_admin, only: [:open_issues]

  # GET /tickets
  # GET /tickets.json
  def index
    if current_user.admin?
      @tickets = Ticket.all
    else
      @tickets = current_user.tickets.where(user_id: current_user)
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @comment = Comment.new
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = current_user.tickets.build(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def open_issues
    @open_issues = Ticket.where("status" == false)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:title, :message, :category, :priority)
    end

    def must_be_admin
      unless current_user.admin?
        redirect_to tickets_path, alert: "You don't have access to this page"
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :must_be_admin

  def index
    @users = User.all
  end

  private

  def must_be_admin
    unless current_user.admin?
      redirect_to tickets_path, alert: "You don't have access to this page"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def readable_time(time)
    time.strftime("%b %d, %I:%M%P")
  end

  def author_of(record)
    user_signed_in? && current_user.id == record.user_id
  end

  def admin?
    user_signed_in? && current_user.admin?
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class="flex items-start p-4 mt-4 border rounded">
  <div class="flex-1 pl-4 flex items-start justify-between">
    <div class="leading-normal">
      <p class="text-gray-700 text-xs"><%= comment.user.username %> commented <%= time_ago_in_words(comment.created_at) %> ago</p>
      <div class="text-gray-700"><%= sanitize comment.reply %></div>
    </div>

    <% if author_of(comment) %>
      <%= link_to "Delete", ticket_comment_path(comment.ticket, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-destroy" %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<p class="text-sm text-gray-600 my-2">comment as <%= current_user.username %></p>

<%= form_for([@ticket, @comment], remote: true) do |f| %>
  <div class="relative">
    <%= f.hidden_field :reply, class: "input h-32 border border-gray-300 resize-none", placeholder: "Add any notes or replies here" %>

    <trix-editor input="comment_reply" id="comment_reply_trix" class="h-32 p-4"></trix-editor>

    <%= f.submit class: "btn btn-small btn-secondary block w-full text-center mt-2 lg: mt-0 lg:text-left lg:absolute lg:pin-b lg:pin-r lg:mb-2 lg:mr-2 lg:w-auto lg:inline-flex" %>
  </div>
<% end %>

app/views/comments/create.js.erb
var comments = document.getElementById("comments");
var commentField = document.getElementById("comment_reply");
var trixField = document.getElementById("comment_reply_trix");
comments.insertAdjacentHTML("beforeend", "<%= escape_javascript(render(@comment)) %>");
commentField.value = "";
trixField.innerHTML = "";

app/views/homes/index.html.erb
<div class="py-10 lg:py-20 px-4 border-b border-gray-200 mb-4 text-indigo-700">
  <div class="container m-auto text-center">
    <h1 class="text-xl lg:text-3xl">Welcome to SupportTicket! </h1>
    <p class="lead my-2 max-w-md m-auto leading-normal text-gray-700 text-lg mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime quaerat maiores, repellat minus fugit, non modi id.</p>

    <% unless user_signed_in? %>
    <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-primary my-3" %>
    <% else %>
    <%#= link_to "Schedule a new session", new_meeting_path, class:"btn btn-primary my-3" %>
    <% end %>
  </div>
</div>


<div class="max-w-lg m-auto">
  <div class="py-10 lg:py-16 px-4 flex flex-wrap items-center justify-between">

    <div class="lg:w-1/2 w-full mb-4 lg:mb-0">
      <h3 class="mb-1">Become a pro in no time</h3>
      <p class="leading-normal">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur commodi similique nihil tempore, possimus, sequi unde illum, officia impedit maxime aut obcaecati. Eligendi officia ipsam et optio, tempore.</p>
    </div>

    <div class="lg:w-1/2 w-full text-center">
    <%= image_tag 'teacher.svg', alt: "Become a pro", width: 400 %>
    </div>
  </div>

  <div class="py-10 lg:py-16 px-4 flex flex-wrap items-center justify-between">
    <div class="lg:w-1/2 w-full mb-4 lg:mb-0">
    <%= image_tag 'move-forward.svg', alt: "Move forward", width: 320 %>
    </div>

    <div class="lg:w-1/2 w-full">
      <h3 class="mb-1">Move foward with your skills</h3>
      <p class="leading-normal">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur commodi similique nihil tempore, possimus, sequi unde illum, officia impedit maxime aut obcaecati. Eligendi officia ipsam et optio, tempore.</p>
    </div>
  </div>
</div>

app/views/layouts/_flash_message.html.erb
<% flash.each do |type, message| %>
  <% if type == "alert" %>
    <div class="bg-red-500">
      <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
    </div>
  <% end %>
  <% if type == "notice" %>
    <div class="bg-green-500">
      <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<header class="bg-white">
  <nav class="flex items-center justify-between flex-wrap bg-gray-100 p-4 text-gray-700 border-b border-gray-200">
    <div class="flex items-center flex-no-shrink mr-6">
      <%= link_to root_path, class:"link text-xl tracking-tight font-semibold" do %>
        SupportTicket
        
      <% end %>
    </div>
    <div class="block lg:hidden">
      <button class="flex items-center px-3 py-2 border rounded text-gray-100 border-gray-100 hover:text-gray-600 hover:border-gray-700">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div class="w-full block lg:flex-1 lg:flex items-center text-center lg:text-left">
      <div class="w-full block lg:flex lg:flex-row lg:flex-1 mt-2 lg:mt-0 text-center lg:text-left lg:justify-end">
        <% unless user_signed_in? %>
        <%= link_to "Login", new_user_session_path, class:"btn btn-default mr-2" %>
        <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default" %>
        <% else %>
        <%= link_to "Dashboard", tickets_path, class: "btn btn-default mr-2" %>
        <%= link_to "Open New Ticket", new_ticket_path, class: "btn btn-default mr-2" unless admin? %>
        <%= link_to "Users", users_path, class: "btn btn-default mr-2" if admin? %>
        <%= link_to "Active Tickets", open_issues_path, class: "btn btn-default mr-2" if admin? %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-default mr-2" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SupportTicket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash_message' %>
    <%= render 'layouts/nav' %>
  
    <main>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/tickets/_form.html.erb
<div class="p-10 mb-5 bg-white border border-gray-300 rounded">
<%= form_with(model: ticket, local: true, class: "ticket-form") do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3 class="mb-4 font-bold">Ticket Information</h3>

  <div class="mb-6">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :category, class: "label" %>
    <%= form.select :category, options_for_select([["Select Category", ""], "Technical", "Work", "Office", "Home", "Other"]), {}, class: "select" %>
  </div>

  <div class="mb-6">
    <%= form.label :priority, class: "label" %>
    <%= form.select :priority, options_for_select([["Select Priority", ""], "Low", "Medium", "High"]), {}, class: "select" %>
  </div>

  <div class="mb-6">
    <%= form.label :message, class: "label" %>
    <%= form.text_area :message, size: "24x6", class: "input" %>
  </div>

  <hr class="border" />

  <%= form.submit class: "btn btn-primary text-base py-3 px-5 mt-2" %>

<% end %>
</div>

app/views/tickets/_tickets_cta.html.erb
<div class="max-w-md my-10 m-auto p-12 lg:p-16 bg-white rounded border border-gray-300 text-center shadow">
  <%= image_tag "schedule.svg", alt: "schedule", width: 300, class: "mb-4" %>
  <h1 class="text-indigo-800 text-2xl mb-6">It looks like you haven't open a ticket yet</h1>
  <%= link_to "Open a new ticket", new_ticket_path, class: "btn btn-primary py-3 px-5" %>
</div>

app/views/tickets/_tickets_landing.html.erb
<nav class="bg-gray-200 mb-4 shadow rounded">
  <ul list-reset>
    <li class="p-5 bg-indigo-700 text-white rounded">
      My Tickets
    </li>
  </ul>
</nav>

<div class="bg-white p-10 border rounded">

     <h1 class="font-bold">All Tickets</h1>

     <div class="flex flex-wrap items-center justify-between border-b-2 p-4 border-gray-300 text-gray-800">
        <p>Category</p>
        <p>Title</p>
        <p>Status</p>
        <p>Last Updated</p>
     </div>

     <% tickets.each do |ticket| %>
        <div class="flex flex-wrap items-center justify-between p-4 border-b border-gray-300 mb-6">
          <div class="flex-1 flex justify-between">
            <div>
              <%= link_to ticket.category, ticket, class: "link mr-4" %>
            </div>
            <div>
              <%= link_to ticket.title, ticket, class: "link mr-4" %>
            </div>
            <div>
              <% if ticket.status == false %>
                <p class="link open text-white mr-4">Open</p>
              <% elsif ticket.status == true %>
                <p class="link close text-white mr-4">Closed</p>
              <% end %>
            </div>
            <div>
              <%= readable_time(ticket.created_at) %>
            </div>
          </div>
        </div>

        <%= link_to "Close ticket", ticket, method: :delete, data: { confirm: "Are you sure? There are no refunds." }, class: "btn btn-destroy ml-4" if admin? %>
     <% end %>
  </div>

</div>

app/views/tickets/edit.html.erb
<div class="max-w-3xl m-auto px-4">
  <h1 class="text-3xl mt-10">Edit ticket</h1>
  <p class="text-lg text-gray-700 mb-6">Having troubles, modify your ticket, you solve your problem below.</p>
  <%= render 'form', ticket: @ticket %>
</div>

app/views/tickets/index.html.erb
<div class="container m-auto my-4">
  <% unless current_user.tickets.any? %>
    <%= render "tickets_cta" %>
  <% else %>
    <%= render "tickets_landing", tickets: @tickets %>
  <% end %>
</div>

app/views/tickets/new.html.erb
<div class="max-w-3xl m-auto px-4">
  <h1 class="text-3xl mt-10">Open a new ticket</h1>
  <p class="text-lg text-gray-700 mb-6">Having troubles, open new ticket for us to help you solve your problem below.</p>
  <%= render 'form', ticket: @ticket %>
</div>

app/views/tickets/open_issues.html.erb
 
<div class="container m-auto bg-white my-10 border border-gray-400 p-10">
<h1 class="text-indigo-800">Open Issues</h1>

 <% @open_issues.each do |ticket| %>
  <div class="flex flex-wrap items-center justify-start p-4 border-b border-gray-400 mb-6">
    <div class="flex-1 flex justify-between">
      <div>
        <%= link_to ticket.title, ticket, class: "link mr-4" %>
      </div>
      <div>
        <%= ticket.category %> &ndash;
        <%= ticket.priority %>
      </div>
    </div>

    <%= link_to 'Close Ticket', ticket, method: :delete, remote: true, data: { confirm: 'Are you sure you want to close this ticket ?' }, class: "btn btn-destroy ml-4" if admin? %>
  </div>
  <% end %>
</div>

app/views/tickets/show.html.erb
<div class="max-w-3xl my-10 m-auto">
  <div class="p-10 bg-white border border-gray-400 rounded">
    <p class="mb-3"><span class="font-bold">Message: </span><%= @ticket.message %></p>
    <p class="mb-3"><span class="font-bold">Category: </span><%= @ticket.category %></p>
    <p class="mb-3">
    <span class="font-bold">Status: </span>
    <% if @ticket.status == false %>
      <span class="link open text-white mr-4">Open</span>
    <% elsif @ticket.status == true %>
      <span class="link close text-white mr-4">Closed</span>
    <% end %></p>
    <p class="mb-3"><span class="font-bold">Created on: </span><%= readable_time(@ticket.created_at) %></p>

    <h4>Comments</h4>
    <hr class="border" />

    <% unless user_signed_in? %>
      <div class="bg-gray-400 rounded p-4 mt-4 text-center">
        <p class="text-sm text-gray-700"><%= link_to "Login", new_user_session_path, class: "link" %> or <%= link_to "Sign up", new_user_regsitration_path, class: "link" %> to comment.</p>
      </div>
    <% else %>
        <%= render 'comments/form' %>
    <% end %>

    <div id="comments" class="mt-10">
      <%= render @ticket.comments %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="flex flex-wrap items-center mb-5 text-indigo-800">
  <div class="flex-1 flex justify-between items-center">
    <div><h3 class="text-lg"><%= user.full_name %></h3> <%= user.username %> <% if current_user %>(You)<% end %></div>
    <p>Joined on <%= readable_time(user.created_at) %></p>

  </div>
  <%= link_to 'Delete User', users_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-destroy ml-4" if admin? %>
</div>

<% if user.tickets.any? %>
  <div class="block pl-2 border-l border-indigo-500 mb-5">
    <p class="text-xs uppercase tracking-loose text-gray-700 pt-1">Ticket Created</p>
    <% user.tickets.each do |ticket| %>
        <%= link_to ticket.title, ticket, class: "link my-3 block" %>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container m-auto bg-white my-10 border border-grey-light p-6">
  <h1 class="text-indigo-darker pb-2 border-b border-grey-light mb-4">All Users</h1>
  <%= render @users %>
</div>